//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFPSViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyFPSViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Azure99 {
            get {
                object obj = ResourceManager.GetObject("Azure99", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;title&gt;Problem&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;div&gt;
        ///    &lt;h2 style=&quot;text-align: center;&quot;&gt;[[[Title]]]&lt;/h2&gt;
        ///    &lt;hr /&gt;
        ///    &lt;div style=&quot;text-align: center;&quot;&gt;
        ///        &lt;p&gt;TimeLimit:[[[TimeLimit]]] | MemoryLimit:[[[MemoryLimit]]]&lt;/p&gt;
        ///    &lt;/div&gt;
        ///    &lt;div&gt;
        ///        &lt;h3&gt;Description&lt;/h3&gt;
        ///        &lt;div style=&quot;background-color: #f0f0f5;&quot;&gt;[[[Description]]]&lt;/div&gt;
        ///        &lt;h3&gt;Input&lt;/h3&gt;
        ///        &lt;div style=&quot;background-color: #f0f0f5;&quot;&gt;[[[Input]]]&lt;/div&gt;
        ///        &lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string FPSWebView {
            get {
                return ResourceManager.GetString("FPSWebView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ##简体中文
        ///File=文件
        ///Load=加载
        ///Save=保存
        ///About=关于
        ///Exit=退出
        ///
        ///Edit=编辑
        ///Clear=清空
        ///Tools=工具
        ///Replace NewLine To \n=替换换行符为\n
        ///Split FPS=切割FPS 的本地化字符串。
        /// </summary>
        internal static string Zh_Cn {
            get {
                return ResourceManager.GetString("Zh_Cn", resourceCulture);
            }
        }
    }
}
